project_application/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^list/$', views.project_application_list, name='project_application_list'),
    url(r'^institute/$', views.project_application_faculty, name='project_application_faculty'),
    url(r'^start/$', views.full_project_application, name='start_project_application'),

    url(r'^(?P<token>.+)/done/$', views.project_application_done, name='project_application_done'),
    url(r'^(?P<token>.+)/parta/$', views.project_application_parta, name='project_application_parta'),
    url(r'^(?P<token>.+)/partb/$', views.project_application_partb, name='project_application_partb'),
    url(r'^(?P<token>.+)/partc/$', views.project_application_partc, name='project_application_partc'),
    url(r'^(?P<token>.+)/pdf/$', views.project_application_pdf, name='project_application_pdf'),
    url(r'^(?P<token>.+)/view/$', views.project_application_view, name='view_project_application'),
    url(r'^(?P<token>.+)/approve/$', views.project_application_approve, name='approve_project_application'),
    url(r'^(?P<token>.+)/decline/$', views.project_application_decline, name='decline_project_application'),
    url(r'^(?P<token>.+)/delete/$', views.project_application_delete, name='delete_project_application'),
    url(r'^(?P<token>.+)/add_comment/$',
                views.project_application_add_comment, name='project_application_add_comment'),
    url(r'^(?P<token>.+)/$', views.submit_project_application, name='project_application_submit'),

    url(r'^$', views.project_application_info, name='linkto_project_application'),
]

urlpatterns = [
    url(r'^apply/', include(urlpatterns)),
]

project_application/models.py
from django.db import models
from django.conf import settings

import datetime

from karaage.common import new_random_token
from karaage.institutes.models import Institute
from karaage.projects.models import Project
from karaage.people.models import Person
from .fields import TextLengthField

import project_application.for_choices as for_choices

class ProjectApplication(models.Model):
    NEW = 'N'
    OPEN = 'O'
    WAITING_FOR_REVIEW = 'L'
    WAITING_FOR_ADMIN = 'K'
    COMPLETE = 'C'
    ARCHIVED = 'A'
    DECLINED = 'R'
    APPLICATION_STATES = (
        (NEW, 'Invitiation Sent'),
        (OPEN, 'Open'),
        (WAITING_FOR_REVIEW, 'Waiting for review'),
        (WAITING_FOR_ADMIN, 'Waiting for Karaage admin processing'),
        (COMPLETE, 'Complete'),
        (ARCHIVED, 'Archived'),
        (DECLINED, 'Declined'),
        )

    secret_token = models.CharField(max_length=64, default=new_random_token, editable=False, unique=True)
    expires = models.DateTimeField()
    created_by = models.EmailField(editable=False)
    created_date = models.DateTimeField(auto_now_add=True, editable=False)
    submitted_date = models.DateTimeField(null=True, blank=True)
    complete_date = models.DateTimeField(null=True, blank=True, editable=False)

    state = models.CharField(max_length=1, choices=APPLICATION_STATES, default=NEW)
    project = models.ForeignKey(Project, null=True, blank=True, related_name='project_application')
    host_institute = models.CharField(max_length=200, null=True, blank=True)
    host_faculty = models.CharField(max_length=200, null=True, blank=True)
    host_school = models.CharField(max_length=200, null=True, blank=True)

    tac = models.BooleanField(default=False)

    FOR = models.CharField(max_length=100, choices=for_choices.FOR_CHOICES)

    # Project Information
    title = models.CharField('Project Title', max_length=100, null=True, blank=True)
    summary = TextLengthField('Summary of Project', null=True, blank=True, max_length=2000)
    purpose = TextLengthField('Suported Activity', null=True, blank=True, max_length=2000)

    # Resource Information
    hardware_request = TextLengthField('Hardware Request', null=True, blank=True, max_length=2000)
    compute_note = TextLengthField('Additional Information', null=True, blank=True, max_length=2000)

    class Meta:
        ordering = ['-id']

    def __unicode__(self):
        return "Project Application #%s" % self.id

    @models.permalink
    def get_absolute_url(self):
        return ('view_project_application', [self.secret_token])


class ProjectApplicationMember(models.Model):
    TITLES = (
        ('Mr', 'Mr'),
        ('Mrs', 'Mrs'),
        ('Miss', 'Miss'),
        ('Ms', 'Ms'),
        ('Dr', 'Dr'),
        ('A/Prof', 'A/Prof'),
        ('Prof', 'Prof'),
    )
    LEVELS = (
        ('E', 'Professor or equivalent'),
        ('D', 'Associate Professor or equivalent'),
        ('C', 'Senior Lecturer or equivalent'),
        ('B', 'Lecturer or equivalent'),
        ('A', 'Research Assistant or equivalent'),
        ('S', 'Student or equivalent'),
    )
    ROLES = (
        ('CI', 'Chief Investigator'),
        ('I', 'Investigator'),
        ('S', 'Student'),
    )
    email = models.EmailField(null=True, blank=True)
    title = models.CharField(choices=TITLES, max_length=100, null=True, blank=True)
    first_name = models.CharField(max_length=30, null=True, blank=True)
    last_name = models.CharField(max_length=30, null=True, blank=True)
    institute = models.CharField(max_length=200, null=True, blank=True)
    faculty = models.CharField(max_length=200, null=True, blank=True)
    department = models.CharField(max_length=200, null=True, blank=True)
    telephone = models.CharField("Office Telephone", max_length=200, null=True, blank=True)
    is_applicant = models.BooleanField(default=False, editable=False)
    is_supervisor = models.BooleanField(default=False)
    is_leader = models.BooleanField(default=False)
    level = models.CharField(choices=LEVELS, max_length=1, null=True, blank=True)
    role = models.CharField(choices=ROLES, max_length=2, null=True, blank=True)
    disp_order = models.PositiveIntegerField(null=True, blank=True)

    project_application = models.ForeignKey(ProjectApplication)

    class Meta:
        unique_together = (('email', 'project_application'),)
        ordering = ['disp_order']

    def __unicode__(self):
        if self.first_name and self.last_name:
            return self.get_full_name()
        if self.email:
            return self.email
        return self.pk

    def get_full_name(self):
        return "%s %s" % (self.first_name, self.last_name)


'''
Want to report usage by Institute, Faculty and School
Unfortunately Karaage doesn't have these, so adding here as a short cut
'''
class ProjectApplicationFaculty(models.Model):
    faculty = models.CharField(max_length=100, null=True, blank=True)
    school = models.CharField(max_length=100, null=True, blank=True)
    institute = models.ForeignKey(Institute, null=True, blank=True)

    class Meta:
        unique_together = (('institute', 'faculty', 'school',),)

project_application/templates/project_application/admin_confirm_decline.html
{% extends "project_application/project_application_forms.html" %}

{% block extrahead %}
{% load staticfiles %}
{% endblock %}

{% block content_title %}Decline Application{% endblock %}

{% block navigation %}
<ul class="nav navbar-nav">
  <li class="active"><a>Decline Application</a></li>
</ul>
{% endblock %}

{% block content %}

<div class="container-fluid">

  <form method="post" action=".">{% csrf_token %}
    {{ form.management_form }}

    {% if form.errors or form.non_field_errors %}
    <div class="alert alert-danger"><span class="glyphicon glyphicon-remove-sign"></span> &nbsp; &nbsp;Please correct any errors below.</div>
    {% endif %}

    {% if form.non_field_errors %}
    {% for err in form.non_field_errors %}
    <div class="alert alert-danger"><span class="glyphicon glyphicon-remove-sign"></span> &nbsp; &nbsp;{{ err }}</div>
    {% endfor %}
    {% endif %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}

    <div class="panel panel-default padtop">
      <div class="panel-heading">
        <h3 class="panel-title">Decline Process</h3>
      </div>
      <div class="panel-body">
        {% if form.non_field_errors %}
        {% for err in form.non_field_errors %}
        <div class="alert alert-danger"><span class="glyphicon glyphicon-remove-sign"></span> &nbsp; &nbsp;{{ err }}</div>
        {% endfor %}
        {% endif %}
        <p>Declining an application marks it as declined.</p>
        <p>The applicant will need to be contacted and informed of why the
        application has been declined.</p>
      </div>
    </div>

    <div class="panel panel-default padtop">
      <div class="panel-heading">
        <h3 class="panel-title">Project Details</h3>
      </div>
      <div class="panel-body">
        <div class="panel panel-default padtop">
          <div class="panel-body">
            <div class="row">
                <div class="col-md-2">
                  <label class="required">Associated/New Project</label>
                </div>
                <div class="col-md-10">
                  {{ project_application.associated }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                  <label class="required">Host Institute, Faculty, School</label>
                </div>
          <p>{{ supervisor.institute|default:"<h6>incomplete</h6>" }},
             {{ supervisor.faculty|default:"<h6>incomplete</h6>" }},
             {{ supervisor.department|default:"<h6>incomplete</h6>" }}
          </p>
            </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="row">
                <div class="col-md-2">
                  <label class="required">Requested/New Title</label>
                </div>
                <div class="col-md-10">
                  {{ project_application.title|default:"<h6>incomplete</h6>" }}
                </div>
            </div>
          </div>
        </div>

    <div class="panel panel-default padtop">
      <div class="panel-heading">
        <h3 class="panel-title">Leaders</h3>
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-striped table-condensed">
            <thead>
              <tr>
                <th><label >Project<br/>Supervisor</label></th>
                <th><label >Applicant</label></th>
                <th><label >Leader</label></th>
                <th><label >Title</label></th>
                <th><label >Given<br/>Name</label></th>
                <th><label >Family<br/>Name</label></th>
                <th><label >Email</label></th>
                <th><label >Institute</label></th>
                <th><label >Faculty</label></th>
                <th><label>Department</label></th>
                <th><label >Contact<br/>Telephone<br/>Number</label></th>
                <th><label >Level</label></th>
                <th><label >Role</label></th>
              </tr>
            </thead>
            <tbody>
              {% for p in members %}
              <tr>
                <td align="center">
                  {% if p.is_supervisor %}
                  <span class="glyphicon glyphicon-ok-sign"></span>
                  {% endif %}
                </td>
                <td align="center">
                  {% if p.is_applicant %}
                  <span class="glyphicon glyphicon-ok-sign"></span>
                  {% endif %}
                </td>
                <td align="center">
                  {% if p.is_leader %}
                  <span class="glyphicon glyphicon-ok-sign"></span>
                  {% endif %}
                </td>
                <td>{{ p.title|default_if_none:"<h6>incomplete</h6>" }}</td>
                <td>{{ p.first_name|default:"<h6>incomplete</h6>" }}</td>
                <td>{{ p.last_name|default:"<h6>incomplete</h6>" }}</td>
                <td>{{ p.email|default:"<h6>incomplete</h6>" }}</td>
                <td>{{ p.institute|default:"<h6>incomplete</h6>" }}</td>
                <td>{{ p.faculty|default:"<h6>incomplete</h6>" }}</td>
                <td>{{ p.department|default:"<h6>left blank</h6>" }}</td>
                <td>{{ p.telephone|default:"<h6>incomplete</h6>" }}</td>
                <td>{{ p.get_level_display|default_if_none:"<h6>incomplete</h6>" }}</td>
                <td>{{ p.get_role_display|default_if_none:"<h6>incomplete</h6>" }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <fieldset>
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="form-group">
            <button class="btn btn-warning" type="submit">Confirm Decline</button>
          </div>
        </div>
      </div>
    </fieldset>
  </form>
</div>
{% endblock %}

project_application/templates/project_application/admin_confirm_delete.html
{% extends "project_application/project_application_forms.html" %}

{% block extrahead %}
{% load staticfiles %}
{% endblock %}

{% block content_title %}Delete Application{% endblock %}

{% block navigation %}
<ul class="nav navbar-nav">
  <li class="active"><a>Delete Application</a></li>
</ul>
{% endblock %}

{% block content %}

<div class="container-fluid">

  <form method="post" action=".">{% csrf_token %}
    {{ form.management_form }}

    {% if form.errors or form.non_field_errors %}
    <div class="alert alert-danger"><span class="glyphicon glyphicon-remove-sign"></span> &nbsp; &nbsp;Please correct any errors below.</div>
    {% endif %}

    {% if form.non_field_errors %}
    {% for err in form.non_field_errors %}
    <div class="alert alert-danger"><span class="glyphicon glyphicon-remove-sign"></span> &nbsp; &nbsp;{{ err }}</div>
    {% endfor %}
    {% endif %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}

    <div class="panel panel-default padtop">
      <div class="panel-heading">
        <h3 class="panel-title">Delete Process</h3>
      </div>
      <div class="panel-body">
        {% if form.non_field_errors %}
        {% for err in form.non_field_errors %}
        <div class="alert alert-danger"><span class="glyphicon glyphicon-remove-sign"></span> &nbsp; &nbsp;{{ err }}</div>
        {% endfor %}
        {% endif %}
        <p>Delete the application if it is incomplete and expired.</p>
        <p>If the application is almost complete, it is worth checking if they wish to submit.</p>
      </div>
    </div>

    <div class="panel panel-default padtop">
      <div class="panel-heading">
        <h3 class="panel-title">Project Details</h3>
      </div>
      <div class="panel-body">
        <div class="panel panel-default padtop">
          <div class="panel-body">
            <div class="row">
                <div class="col-md-2">
                  <label class="required">Associated/New Project</label>
                </div>
                <div class="col-md-10">
                  {{ project_application.associated }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                  <label class="required">Host Institute, Faculty, School</label>
                </div>
          <p>{{ supervisor.institute|default:"<h6>incomplete</h6>" }},
             {{ supervisor.faculty|default:"<h6>incomplete</h6>" }},
             {{ supervisor.department|default:"<h6>incomplete</h6>" }}
          </p>
            </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="row">
                <div class="col-md-2">
                  <label class="required">Requested/New Title</label>
                </div>
                <div class="col-md-10">
                  {{ project_application.title|default:"<h6>incomplete</h6>" }}
                </div>
            </div>
          </div>
        </div>

    <div class="panel panel-default padtop">
      <div class="panel-heading">
        <h3 class="panel-title">Leaders</h3>
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-striped table-condensed">
            <thead>
              <tr>
                <th><label >Project<br/>Supervisor</label></th>
                <th><label >Applicant</label></th>
                <th><label >Leader</label></th>
                <th><label >Title</label></th>
                <th><label >Given<br/>Name</label></th>
                <th><label >Family<br/>Name</label></th>
                <th><label >Email</label></th>
                <th><label >Institute</label></th>
                <th><label >Faculty</label></th>
                <th><label>Department</label></th>
                <th><label >Contact<br/>Telephone<br/>Number</label></th>
                <th><label >Level</label></th>
                <th><label >Role</label></th>
              </tr>
            </thead>
            <tbody>
              {% for p in members %}
              <tr>
                <td align="center">
                  {% if p.is_supervisor %}
                  <span class="glyphicon glyphicon-ok-sign"></span>
                  {% endif %}
                </td>
                <td align="center">
                  {% if p.is_applicant %}
                  <span class="glyphicon glyphicon-ok-sign"></span>
                  {% endif %}
                </td>
                <td align="center">
                  {% if p.is_leader %}
                  <span class="glyphicon glyphicon-ok-sign"></span>
                  {% endif %}
                </td>
                <td>{{ p.title|default_if_none:"<h6>incomplete</h6>" }}</td>
                <td>{{ p.first_name|default:"<h6>incomplete</h6>" }}</td>
                <td>{{ p.last_name|default:"<h6>incomplete</h6>" }}</td>
                <td>{{ p.email|default:"<h6>incomplete</h6>" }}</td>
                <td>{{ p.institute|default:"<h6>incomplete</h6>" }}</td>
                <td>{{ p.faculty|default:"<h6>incomplete</h6>" }}</td>
                <td>{{ p.department|default:"<h6>left blank</h6>" }}</td>
                <td>{{ p.telephone|default:"<h6>incomplete</h6>" }}</td>
                <td>{{ p.get_level_display|default_if_none:"<h6>incomplete</h6>" }}</td>
                <td>{{ p.get_role_display|default_if_none:"<h6>incomplete</h6>" }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <fieldset>
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="form-group">
            <button class="btn btn-danger" type="submit">Confirm Deletion</button>
          </div>
        </div>
      </div>
    </fieldset>
  </form>
</div>
{% endblock %}

project_application/templates/project_application/footer.html
<div class="navbar navbar-default">                                                                                                 
  <div class="container-fliud">                                             
    <ul class="nav navbar-nav">                                             
      <li><a href="/" target="{{ org_name }}">{{ org_name }}</a></li>
      <li><a href="/help" target="Help">Help Desk</a></li>
      <li><a href="{{ AUP_URL }}" target="TaC">Terms and Conditions</a></li>
    </ul>                                                                   
  </div>                                                                    
</div>                                                                      

project_application/templates/project_application/old_userapplication.html
{% extends "project_application/project_application_forms.html" %}


{% block navigation %}
  <ul class="nav navbar-nav">
    <li class="active"><a>Link Not Found</a></li>
  </ul>
{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="panel panel-default padtop">
    <div class="panel-heading">
      <h4 class="panel-title">Link Not Found</h4>
    </div>
    <div class="panel-body">
      <p>This application is no longer viewable. This could be due to:</p>
      <ul>
        <li>The application has expired.</li>
        <li>You have already submitted the application.</li>
        <li>There is an error in the link (the link may be broken across two lines).</li>
        <li>The application has been modified by an administrator.</li>
      </ul>
      <p>If you have any comments or enquiries, please contact {{ help_email|urlize }}</p>
    </div>
  </div>
</div>
{% endblock %}

project_application/templates/project_application/project_application_done.html
{% extends "project_application/project_application_forms.html" %}

{% block title %}Submitted{% endblock %}


{% block navigation %}
  <ul class="nav navbar-nav">
    <li class="active"><a>Submitted</a></li>
  </ul>
{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="panel panel-default padtop">
    <div class="panel-heading">
      <h4 class="panel-title">Submitted</h4>
    </div>
    <div class="panel-body">
      <p>Thank you for submitting {{ org_name }} Resource Application #{{ project_application.id }}</p>
      <p>An e-mail has been sent to you at: {{ email }} with a PDF version of the application.</p>
      <p>If you have any comments or enquiries, please contact: {{ help_email|urlize }}</a></p>
    </div>
  </div>
</div>
{% endblock %}

project_application/templates/project_application/project_application_info.html
{% extends "project_application/project_application_forms.html" %}

{% block title %}New Project Application Information{% endblock %}

{% block navigation %}
  <ul class="nav navbar-nav">
    <li class="active"><a>Getting Started</a></li>
  </ul>
{% endblock %}

{% block content %}
<div class="container-fluid">
  <h3>Welcome to the {{ org_name }} Project Application website.</h3>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Note</h3>
    </div>
    <div class="panel-body">
      <p>Project applications are managed by the e-mail address that you provided during the application process.<br/>
  Institutional e-mail addresses are required.</p>
      <p>Every project <strong>must</strong> have a Project Supervisor*.
        <br/>
        It is recommended that the applicant is the Project Supervisor.
      </p>
      <div class="alert alert-danger" role="alert">
        <p>Students can not be the Project Supervisor</p>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <p class="text-muted">* The Project Supervisor (Chief Principle Investigator) is responsible for the larger scientific context of the work and generally hold the overarching funding grant of the project.  They will be responsible for all resource usage, including data management.  All compute, storage and software resources are accounted and reported to the Supervisor's Host institute.
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title">New Project Application</h4>
    </div>
    <div class="panel-body">
        <p>Start a New Project Application</p>
        </div>
    <div class="panel-footer">
        <button type="button" class="btn btn-primary" onClick="parent.location='{% url 'start_project_application' %}'">Start</button>
    </div>
  </div>
</div>
{% endblock %}

project_application/templates/project_application/project_application_view.html
{% extends "project_application/project_application_forms.html" %}

{% load karaage_tags %}

{% load staticfiles %}

{% block content_title %}Submitted Application Details{% endblock %}

{% block navigation %}
  <ul class="nav navbar-nav">
    <li class="active"><a>Submitted Details</a></li>
  </ul>
  {% if is_admin %}
  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><a href="{% url 'project_application_submit' project_application.secret_token %}">Edit</a></li>
        <li role="separator" class="divider"></li>
        <li><a href="{% url 'approve_project_application' project_application.secret_token %}">Approve</a></li>
        <li><a href="{% url 'decline_project_application' project_application.secret_token %}">Decline</a></li>
        <li role="separator" class="divider"></li>
        <li><a class="btn-danger" href="{% url 'delete_project_application' project_application.secret_token %}">Delete</a></li>
      </ul>
  {% endif %}
    </li>
  </ul>
{% endblock %}
  
{% block content %}
    <div class="container-fluid">
      {% if is_admin %}
        {% if project_application.submitted_date %}
          <p class="lead padtop">Submitted: {{ project_application.submitted_date|date:"l j F Y" }}</p>
        {% else %}
          <p class="lead padtop">Not yet submitted</p>
        {% endif %}

<div class="container-fluid">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Reviewer/Administrator Comments</h3>
      </div>
      <div class="panel-body">
        {% comments project_application %}
        <span class="help-block">Please add any comments here to help with the processing of this application.</span>
        <p class="help-block">Please include Ticket Number and assessment</p>
      </div>
      <div class="panel-footer">
        <button class="btn btn-default" OnClick="parent.location='{% url 'project_application_add_comment' project_application.secret_token %}'" > Add Comment </button>
      </div>
    </div>

  </div>

      {% else %}
        <p class="lead padtop">This application has been submitted.</p>
        <p>This page will be viewable until <strong>11:59pm {{ project_application.expires|date:"l j F Y" }}</strong></p>
      {% endif %}
  
      <div class="panel panel-default padtop">
        <div class="panel-heading">
          <h3 class="panel-title">Host Institute, Faculty and Department</h3>
        </div>
        <div class="panel-body">
          <p>{{ supervisor.institute|default:"<h6>incomplete</h6>" }},
             {{ supervisor.faculty|default:"<h6>incomplete</h6>" }},
             {{ supervisor.department|default:"<h6>incomplete</h6>" }}
          </p>
        </div>
      </div>

      <div class="panel panel-default padtop">
        <div class="panel-heading">
          <h3 class="panel-title">Personnel</h3>
        </div>
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table table-striped table-condensed">
              <thead>
                <tr>
                  <th><label >Project<br/>Supervisor</label></th>
                  <th><label >Applicant</label></th>
                  <th><label >Leader</label></th>
                  <th><label >Title</label></th>
                  <th><label >Given<br/>Name</label></th>
                  <th><label >Family<br/>Name</label></th>
                  <th><label >Email</label></th>
                  <th><label >Institute</label></th>
                  <th><label >Faculty</label></th>
                  <th><label>Department</label></th>
                  <th><label >Contact<br/>Telephone<br/>Number</label></th>
                  <th><label >Level</label></th>
                  <th><label >Role</label></th>
                </tr>
              </thead>
              <tbody>
                {% for p in members %}
                  <tr>
                    <td align="center">
                      {% if p.is_supervisor %}
                        <span class="glyphicon glyphicon-ok-sign"></span>
                      {% endif %}
                    </td>
                    <td align="center">
                      {% if p.is_applicant %}
                        <span class="glyphicon glyphicon-ok-sign"></span>
                      {% endif %}
                    </td>
                    <td align="center">
                      {% if p.is_leader %}
                        <span class="glyphicon glyphicon-ok-sign"></span>
                      {% endif %}
                    </td>
                    <td>{{ p.title|default_if_none:"<h6>incomplete</h6>" }}</td>
                    <td>{{ p.first_name|default:"<h6>incomplete</h6>" }}</td>
                    <td>{{ p.last_name|default:"<h6>incomplete</h6>" }}</td>
                    <td>{{ p.email|default:"<h6>incomplete</h6>" }}</td>
                    <td>{{ p.institute|default:"<h6>incomplete</h6>" }}</td>
                    <td>{{ p.faculty|default:"<h6>incomplete</h6>" }}</td>
                    <td>{{ p.department|default:"<h6>incomplete</h6>" }}</td>
                    <td>{{ p.telephone|default:"<h6>incomplete</h6>" }}</td>
                    <td>{{ p.get_level_display|default_if_none:"<h6>incomplete</h6>" }}</td>
                    <td>{{ p.get_role_display|default_if_none:"<h6>incomplete</h6>" }}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Project Overview</h3>
        </div>
        <div class="list-group">
          <div class="list-group-item">
            <label class="list-group-label required">Project Title:</label>
            <p class="list-group-text">{{ project_application.title|default:"<h6>incomplete</h6>" }}
          </div>
          <div class="list-group-item">
            <label class="list-group-label required">Field of Research:</label>
            <p class="list-group-text">{{ project_application.get_FOR_display|default:"<h6>incomplete</h6>"|linebreaksbr }}</p>
          </div>
          <div class="list-group-item">
            <label class="list-group-label required">Summary of Proposal:</label>
            <p class="list-group-text">{{ project_application.summary|default:"<h6>incomplete</h6>"|linebreaksbr }}</p>
          </div>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Resource Requirements</h3>
        </div>
        <div class="panel-body">
          <p>{{ project_application.hardware_request|default:"<h6>left blank</h6>"|linebreaksbr }}</p>
        </div>
      </div>

      <div class="panel panel-default padtop">
        <div class="panel-heading">
          <h3 class="panel-title">Additional Information</h3>
        </div>
        <div class="panel-body">
          <p>{{ project_application.compute_note|default:"<h6>left blank</h6>"|linebreaksbr }}</p>
        </div>
      </div>

      <div class="panel-footer">
        <div class="form-group">
          <button class="btn btn-default" OnClick="parent.location='{% url 'project_application_pdf' project_application.secret_token %}'" > PDF </button>
        </div>
      </div>
</div>
{% endblock %}